# Generated by Django 3.1.7 on 2021-03-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('university', '0002_auto_20210310_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='task_id',
        ),
        migrations.AddField(
            model_name='university',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='task_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
